### ISSUE TITLE
Unchecked block possibly allows griefing attacks

### ISSUE THREAD

**Issue by beepidibop** [pr0toshi/rateLimit#1]
If a small withdrawal is made, the contract may be locked for the duration of `timeLimit` due to underflows making the `rateLimit` check fail.

E.g.
1. Make small withdrawal
2. Wait some time so unchecked block underflows `info.rate`
3. Try withdrawing again, `info.rate` either reverts due to overflows or fails the `rateLimit` check

**Comment by pr0toshi** [comment]
Can you explain how the block would underflow?

**Comment by pr0toshi** [comment]
For reference the current implementation can be found here.
https://github.com/pr0toshi/EIPs/blob/patch-1/EIPS/EIPs/eip-5075.md

This was moreso for after the proposal gets accepted for implementations

**Comment by pr0toshi** [comment]
The underflows and a few other problems were fixed
